const quotes = [
	"Better to remain silent and be thought a fool than to speak out and remove all doubt.\n– Abraham Lincoln",
	"If I were two-faced, would I be wearing this one?\n– Abraham Lincoln",
	"The best thing about the future is that it comes one day at a time.\n– Abraham Lincoln",
	"The only mystery in life is why the kamikaze pilots wore helmets.\n– Al McGuire",
	"Light travels faster than sound. This is why some people appear bright until you hear them speak.\n– Alan Dundes",
	"Nobody realizes that some people expend tremendous energy merely to be normal.\n– Albert Camus",
	"Men marry women with the hope they will never change. Women marry men with the hope they will change. Invariably they are both disappointed.\n– Albert Einstein",
	"The difference between stupidity and genius is that genius has its limits.\n– Albert Einstein",
	"All the things I really like to do are either immoral, illegal or fattening.\n– Alexander Woollcott",
	"War is God’s way of teaching Americans geography.\n– Ambrose Bierce",
	"It would be nice to spend billions on schools and roads, but right now that money is desperately needed for political ads.\n– Andy Borowitz",
	"The average dog is a nicer person than the average person.\n– Andy Rooney",
	"At every party there are two kinds of people – those who want to go home and those who don’t. The trouble is, they are usually married to each other.\n– Ann Landers",
	"If you want your children to listen, try talking softly to someone else.\n– Ann Landers",
	"Doctors are just the same as lawyers; the only difference is that lawyers merely rob you, whereas doctors rob you and kill you too.\n– Anton Chekhov",
	"I don’t believe in astrology; I’m a Sagittarius and we’re skeptical.\n– Arthur C. Clarke",
	"My opinions may have changed, but not the fact that I’m right.\n– Ashleigh Brilliant",
	"To be sure of hitting the target, shoot first, and call whatever you hit the target.\n– Ashleigh Brilliant",
	"Trouble knocked at the door, but, hearing laughter, hurried away.\n– Benjamin Franklin",
	"Wine is constant proof that God loves us and loves to see us happy.\n– Benjamin Franklin",
	"Have you noticed that all the people in favor of birth control are already born?\n– Benny Hill",
	"Be who you are and say what you feel, because those who mind don’t matter and those who matter don’t mind.\n– Bernard Baruch",
	"Most people would sooner die than think; in fact, they do so.\n– Bertrand Russell",
	"The world is full of magical things patiently waiting for our wits to grow sharper.\n– Bertrand Russell",
	"Facebook just sounds like a drag, in my day seeing pictures of peoples vacations was considered a punishment.\n– Betty White",
	"Everything that used to be a sin is now a disease.\n– Bill Maher",
	"If there is anything the nonconformist hates worse than a conformist, it’s another nonconformist who doesn’t conform to the prevailing standard of nonconformity.\n– Bill Vaughan",
	"Money won’t buy happiness, but it will pay the salaries of a large research staff to study the problem.\n– Bill Vaughan",
	"The surest sign that intelligent life exists elsewhere in the universe is that it has never tried to contact us.\n– Bill Watterson",
	"Before you judge a man, walk a mile in his shoes. After that who cares?… He’s a mile away and you’ve got his shoes!\n– Billy Connolly",
	"I’ve always wanted to go to Switzerland to see what the army does with those wee red knives.\n– Billy Connolly",
	"Going to church doesn’t make you a Christian any more than going to a garage makes you an automobile.\n– Billy Sunday",
	"If you’re going to tell people the truth, be funny or they’ll kill you.\n– Billy Wilder",
	"A bank is a place that will lend you money if you can prove that you don’t need it.\n– Bob Hope",
	"Inside me there’s a thin person struggling to get out, but I can usually sedate him with four or five cupcakes.\n– Bob Thaves",
	"We never really grow up, we only learn how to act in public.\n– Bryan White",
	"As a child my family’s menu consisted of two choices: take it or leave it.\n– Buddy Hackett",
	"But the fact that some geniuses were laughed at does not imply that all who are laughed at are geniuses. They laughed at Columbus, they laughed at Fulton, they laughed at the Wright Brothers. But they also laughed at Bozo the Clown.\n– Carl Sagan",
	"My favorite machine at the gym is the vending machine.\n– Caroline Rhea",
	"All right everyone, line up alphabetically according to your height.\n– Casey Stengel",
	"He who laughs last didn’t get the joke.\n– Charles de Gaulle",
	"I always arrive late at the office, but I make up for it by leaving early.\n– Charles Lamb",
	"Don’t worry about the world coming to an end today. It is already tomorrow in Australia.\n– Charles M. Schulz",
	"By the time a man realizes that his father was right, he has a son who thinks he’s wrong.\n– Charles Wadsworth",
	"A day without laughter is a day wasted.\n– Charlie Chaplin",
	"Political correctness is tyranny with manners.\n– Charlton Heston",
	"High heels were invented by a woman who had been kissed on the forehead.\n– Christopher Morley",
	"If you love something set it free, but don’t be surprised if it comes back with herpes.\n– Chuck Palahniuk",
	"When I was a boy I was told that anybody could become President. I’m beginning to believe it.\n– Clarence Darrow",
	"A stockbroker urged me to buy a stock that would triple its value every year. I told him, ‘At my age, I don’t even buy green bananas.'\n– Claude Pepper",
	"They say marriages are made in Heaven. But so is thunder and lightning.\n– Clint Eastwood",
	"I’m too drunk to taste this chicken.\n– Colonel Sanders",
	"A study in the Washington Post says that women have better verbal skills than men. I just want to say to the authors of that study: ‘Duh.'\n– Conan O’Brien",
	"Starbucks says they are going to start putting religious quotes on cups. The very first one will say, ‘Jesus! This cup is expensive!'\n– Conan O’Brien",
	"Laughing at our mistakes can lengthen our own life. Laughing at someone else’s can shorten it.\n– Cullen Hightower",
	"If you can’t live without me, why aren’t you dead already?\n– Cynthia Heimel",
	"If you think you are too small to make a difference, try sleeping with a mosquito.\n– Dalai Lama",
	"Remember, today is the tomorrow you worried about yesterday.\n– Dale Carnegie",
	"Education is learning what you didn’t even know you didn’t know.\n– Daniel J. Boorstin",
	"It is a scientific fact that your body will not absorb cholesterol if you take it from another person’s plate.\n– Dave Barry",
	"Never under any circumstances take a sleeping pill and a laxative on the same night.\n– Dave Barry",
	"I used to jog but the ice cubes kept falling out of my glass.\n– David Lee Roth",
	"Everyone has a purpose in life. Perhaps yours is watching television.\n– David Letterman",
	"The digital camera is a great invention because it allows us to reminisce. Instantly.\n– Demetri Martin",
	"A failure is like fertilizer; it stinks to be sure, but it makes things grow faster in the future.\n– Denis Waitley",
	"Biologically speaking, if something bites you it’s more likely to be female.\n– Desmond Morris",
	"As long as people will accept crap, it will be financially profitable to dispense it.\n– Dick Cavett",
	"A pessimist is a person who has had to listen to too many optimists.\n– Don Marquis",
	"The cure for boredom is curiosity. There is no cure for curiosity.\n– Dorothy Parker",
	"Never doubt the courage of the French. They were the ones who discovered that snails are edible.\n– Doug Larson",
	"To err is human; to admit it, superhuman.\n– Doug Larson",
	"Human beings, who are almost unique in having the ability to learn from the experience of others, are also remarkable for their apparent disinclination to do so.\n– Douglas Adams",
	"I refuse to answer that question on the grounds that I don’t know the answer.\n– Douglas Adams",
	"There is a theory which states that if ever anyone discovers exactly what the Universe is for and why it is here, it will instantly disappear and be replaced by something even more bizarre and inexplicable.There is another theory which states that this has already happened.\n– Douglas Adams",
	"Don’t cry because it’s over. Smile because it happened.\n– Dr. Seuss",
	"I was born to make mistakes, not to fake perfection.\n– Drake",
	"An alcoholic is someone you don’t like who drinks as much as you do.\n– Dylan Thomas",
	"Analyzing humor is like dissecting a frog. Few people are interested and the frog dies of it.\n– E. B. White",
	"If you think nobody cares if you’re alive, try missing a couple of car payments.\n– Earl Wilson",
	"The duty of a patriot is to protect his country from its government.\n– Edward Abbey",
	"Do not take life too seriously. You will never get out of it alive.\n– Elbert Hubbard",
	"A woman is like a tea bag – you can’t tell how strong she is until you put her in hot water.\n– Eleanor Roosevelt",
	"My grandmother started walking five miles a day when she was sixty. She’s ninety-seven now, and we don’t know where the hell she is.\n– Ellen DeGeneres",
	"A computer once beat me at chess, but it was no match for me at kick boxing.\n– Emo Philips",
	"How many people here have telekenetic powers? Raise my hand.\n– Emo Philips",
	"I asked God for a bike, but I know God doesn’t work that way. So I stole a bike and asked for forgiveness.\n– Emo Philips",
	"Leave something for someone but dont leave someone for something.\n– Enid Blyton",
	"Never go to a doctor whose office plants have died.\n– Erma Bombeck",
	"Never have more children than you have car windows.\n– Erma Bombeck",
	"I drink to make other people more interesting.\n– Ernest Hemingway",
	"Great art is the contempt of a great man for small art.\n– F. Scott Fitzgerald",
	"You’re only as good as your last haircut.\n– Fran Lebowitz"
];

const quote = function(req, res, next) {
    return quotes[Math.floor(Math.random()*quotes.length)];
    //next();
}

module.exports = quote;